### ISSUE TITLE
None of my Clone Hero songs are playing sound

### ISSUE THREAD

**Issue by pdrgrl** [peancored/genuine-hero#1]
I've managed to import my Clone Hero songs, but none of them play with sound, known bug?

**Comment by tonygoldcrest** [comment]
Thanks for reporting!

Which OS do you use?

**Comment by tonygoldcrest** [comment]
Also, can you please attach a screenshot of what your sheet music view looks like?

**Comment by pdrgrl** [comment]
Hi!

I'm running Windows 11 23H2

![image](https://github.com/peancored/drum-hero/assets/32430923/55cc8253-8e9a-49c8-9292-e26ffbd98035)

If there's any other information you'll need me to provide, please let me know.
Thank you!

**Comment by tonygoldcrest** [comment]
That's interesting.
For this song, could you provide the contents of the folder that contains it, with file extensions?

Also, would you be able to clone the repo and build a development version of the app to run a debugger?

**Comment by tonygoldcrest** [comment]
Ah, I think I know what the issue is!
It seems that you're trying to play custom songs (non-Rock Band/Guitar Hero) and the audio files are in `.opus` format?

**Comment by tonygoldcrest** [comment]
Please, try [the latest release](https://github.com/peancored/drum-hero/releases/tag/v0.2.1) and let me know if it addresses the issue.

Please, press the green button to rescan the songs when you do.

**Comment by pdrgrl** [comment]
oh wow! it's working wonderfully now, this is amazing, I can actually single out the drums. 

Thank you so much!!

Btw quick question, I just tried a song and the sheets were empty but the song was playing, I'm assuming that's a problem related with the files of the song and not with your program. I can open another issue, if you wish.

Thank you again!!

**Comment by tonygoldcrest** [comment]
Great that it worked 👍 

Feel free to report it and create another issue, but if it's a single song that doesn't work I'm probably not going to investigate it right now as I'm quite busy with other projects.

It will be useful though if you can provide a link to the place I can download the song in question (for example google drive). In this case there's a higher chance I'm going to fix it sooner rather than later.
